version: '3.8'
services:
  postgres_db:
    image: postgres:13
    ports:
      - "5434:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - trenscendence
networks:
  trenscendence: