services:
  postgresql:
    image: postgres:15-bookworm
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - transcendence
    volumes:
      - type: volume
        target: /mnt/nfs/homes/odessein/Project/ft_transcendence/backend/docker-compose.yml
    ports:
      - "5432:5432"
    restart: always

#volumes:
#  postgres:
#    name: postgres
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /mnt/nfs/homes/ppajot/data/postgres_db

networks:
  transcendence:
    driver: bridge
