services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres_db"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    networks:
      - transcendence
  #  volumes:
  #     - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

#volumes:
#  postgres:
#    name: postgres
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /mnt/nfs/homes/ppajot/data/postgres_db

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - transcendence
    depends_on:
      - postgres
    restart: always

networks:
  transcendence:
    driver: bridge