-- AlterTable
ALTER TABLE "users" ALTER COLUMN "friends" SET DEFAULT ARRAY[-1]::INTEGER[],
ALTER COLUMN "friendsRequest" SET DEFAULT ARRAY[-1]::INTEGER[],
ALTER COLUMN "blocked" SET DEFAULT ARRAY[-1]::INTEGER[];
