services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres_db"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - postgres:/data/postgres_db
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    postgres:
      external: true